version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.19.0
    commands:
    - echo Executing Install Phase

  pre_build:
    commands:
      - echo Executing Pre_Build Phase
      - npm i
      - npm install next -g
  build:
    commands:
    - echo Executing Build Phase on `date`
    - npm run build

artifacts:
  files:
    - '**/*'